%YAML:1.0 # need to specify the file type at the top!

wheel:
  noise_w: 0.015
  noise_v: 0.015
  # noise_p: 0.1
  chi2_mult: 2
  # timeoffset: 0.0
  # intrinsics: [0.3, 0.3, 1.5]
  topic: "/odometry/filtered"
  do_calib_ext: false

  T_imu_wheel:
    - [0.0, 1.0, 0.0, 0.0]
    - [-1.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
